- CHANGELOG.md
- Makefile
- main.go
- version.go
The extension shouldn't panic when unable to make a successful subscription request to the logs API - just output a warning log message. Also, adding a user agent string with a version.
> Remove unnecessary panic when unable to subscribe to logs

- .circleci/config.yml
I haven't added lambda layer publishing yet, that'll likely involve a shell script in addition to a circle config, but this gives us what we need to start distributing the binary at least.
> Add publish steps

- logsapi/client.go
The Logs API will return a 202 on successful subscribe requests. This
should allow that to succeed, as well as future possible responses that
are not 4xx or 5xx.
> Accept broader range of status codes.

- .circleci/config.yml
- publish.sh
Instead of manually releasing the honeycomb-lambda-extension, we can now rely on CI to deploy a new version on tags. If the tag has a suffix of "dev", such as `v5.0.0dev`, then the extension will be published as `honeycomb-lambda-extension-dev`. This will be handy for pre-release testing.
> automate publishing of honeycomb-extension through CI and tagging

- logsapi/client.go
- logsapi/server.go
- logsapi/server_test.go
Fixes #11. The AWS Lambda Logs API provides `function` and `platform` log messages. For `platform` messages (such as function invocation start and end events), use the log message timestamp. For function log messages, which are events written to standard output from a lambda function, look to see if there is a provided timestamp in the string encoded JSON body of the message event. If there is, use it. If not, look to see if there is a `duration_ms` field in the string encoded JSON body. If a duration exists, take the log message timestamp and subtract the duration to get an approximation of start time for the span. If neither of these fields exists, or if the log message body is not JSON, just use the log message timestamp like we do for `platform` messages.
> Use timestamps from body of log message

- main.go
- extension freezes between lambda invocations
- flushing events on every wake is more deterministic
- following aws example: https://github.com/aws-samples/aws-lambda-extensions/blob/b11f8b4ea115bb16eb00603c88e21563f849b15b/go-example-logs-api-extension/main.go#L100
> Flush events queue on wake up

- README.md
- version.go
- version is used in libhoney agent string (looks like we missed updating it for last release)
- tags are ahead of extension version :(
- this will be extension version 6, tag v7.0.0
> Prepare release

- extension/client.go
- logsapi/server.go
- main.go
logrus was never told what level to log at, so we wouldn't see debug statements.
Adds some debug statements to the logsapi.handler which is the most interesting place for learning what's going on in the parsing of log output and its transformation into Honeycomb events.
> add some configurable logging

- logsapi/server.go
- main.go
- when extension is unable to send events to Honeycomb, users have no way to investigate the issue
- add response queue reader when debugging
- swap the (undocumented) log level for debug for simplicity
> Add debugging mode

- README.md
- publish.sh
- new layer version 3 because name is different
- aws only supports architecture compatibility in certain regions
- regions with no support: publish x86_64 (no compatible arch flag)
- regions with support: publish both x86_64 and arm64 (with compatible flag)
- update layer version to 3 --> version reset because of layer name change
> fix: split publish based on region support

- .circleci/config.yml
- README.md
- publish.sh
- previous layer version did not use a directory named `extensions` in the layer zip file
-
> Vera.fix publish again

- CHANGELOG.md
- RELEASING.md
- main.go
- version.go
- changed the user-agent to include <arch> because layer version reset with the new layer names
- we don't know arch because it's only known at binary build time
> Prepare for 10.0.1 release (layer version should be 5)

- .circleci/config.yml
- removed nested extensions dir in #55 but missed the `ls`
- synced manually last release, which failed sync in CI, so this is just prep for next time we release
> ci: fix s3 sync job

- go.mod
- go.sum
Pulls in the [latest libhoney-go](https://github.com/honeycombio/libhoney-go/releases/tag/v1.15.6), fixing an issue where we'll sometimes send invalid JSON to the Honeycomb API, which results in the entire batch being dropped.
> bump libhoney-go

- CHANGELOG.md
- version.go
Prepare v10.0.2 release.
- update version.go to "6"
- add entry to changelog
> Prepare v10.0.2 release

- main.go
The current libhoney user agent addition includes the literal `<arch>`, eg `libhoney-go/1.15.4 honeycomb-lambda-extension-<arch>/5`. It would be nice to have the actual architecture instead.
`runtime.GOARCH` will be "amd64" or "arm64", which doesn't precisely match the releases using "arm64" and "x86_64", but it's better than nothing, I think?
> put GOARCH into user agent

- main.go
- the extension is currently using a less efficient transport encoding
- closes #67 
- configure libhoney client to use msgpack
> feat: use msgpack encoding when sending telemetry

- eventprocessor/eventprocessor.go
- eventprocessor/eventprocessor_test.go
- extension/client.go
- main.go
This PR adds an additional shutdown reason event that is emitted on abnormal Lambda shutdowns. This provides a way to identify when a Lambda function execution timed out or had some type of failure like an out of memory condition. 
* For any abnormal Lambda shutdown, this change emits an additional event that includes the shutdown reason, request id, and function ARN. The shutdown phase of the Lambda extension API (https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html) provides a 'shutdownReason' that is set to `spindown`/`timeout`/`failure`, and this PR uses that information to create the event. 
* It was difficult to write tests with everything in main, so the primary event loop was relocated to a new package, and unit tests were written for it there.
> feat: add shutdown reason event for timeouts and failures

- README.md
- [release 10.2.0](https://github.com/honeycombio/honeycomb-lambda-extension/pull/80) updated the lambda version to 9, but our readme still reflects 7 .
- update readme to reflect lambda layer 9
> maint: update readme to reflect lambda layer 9

- publish.sh
- Adds support for more AWS regions
- Closes #87 
- Add support for the following regions
- af-south-1
- ap-east-1
- eu-south-1
- me-south-1
- According to [AWS](https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/), none of these regions are Arm-processor supported.
> Add support for more AWS regions

- CHANGELOG.md
- README.md
- RELEASING.md
- version.go
- Patch release to rebuild which will fix the latest OpenSSL CVE
- A release PR to trigger rebuild
- Docs PR: https://github.com/honeycombio/docs/pull/1365
> Prep release 10.3.0

- publish.sh
- closes #91 
- Add ap-southeast-3 and ap-northeast-3 to list of regions to publish. Note they are added to `REGIONS_NO_ARCH` as they only support x86_64 and not arm64.
> add missing default regions

- main.go
- Follow up to #98
- We were warning if when the env var was not set. Stop doing that by moving the warn inside the if-statement checking for variable existence.
> (no changelog): only warn about invalid TIMEOUT env var if it is set

- .circleci/config.yml
- .gitignore
- Makefile
- main.go
- publish.sh
- version.go
Release woes, enumerated below with the changes.
- Closes #82 
- Rename published layer in regions to `honeycomb-lambda-extension-<arch>-<version tag>` so that our layer versions will always be `:1`
- Some changes in service towards #95, but not fully producing a release.json yet
Make is good at knowing how to _make_ files. This moves the layer contents
zip creation from the publish script to the Makefile. There's some duplication,
but I think that keeps the Making more readable. CI updated to use the `zip`
make target to build the binaries _and_ the zip files for artifact storage and
workflow pass-along.
Publish script updated to record the results of AWS API calls to files instead of
to script variables or the console. With the results recorded on the filesystem,
we can see …
> maint: release process updates for friendlier ARNs

- .github/release.yml
- make it easier to let automation do the work of generating release notes
- add release.yml to [specify configuration of header sections](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes) for gh release notes organization
- will need to add "no-changelog" label to [list of labels](https://github.com/honeycombio/oss-management/blob/v1/labels/labels.js) to use for each repo - this will primarily be helpful for release prep PRs to not be included in the release notes
> maint: add config for gh release notes organization

- .circleci/config.yml
This is a follow-up fix to the build/release overhaul in #103.
A similar change was made in multiple places, but the publish_s3 job was missed:
* In #103 for [an OS-specific directory ZIP files will be created in](https://github.com/honeycombio/honeycomb-lambda-extension/pull/103/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R61-R90)
* In #108 for [publishing assets to the GitHub Release from the Linux-specific directory](https://github.com/honeycombio/honeycomb-lambda-extension/pull/108/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R76)
With this PR's change, the built artifacts will appear in S3 directly under the `honeycomb-lambda-extension/<VERSION>` subdirectory of the honeycomb-builds bucket to match the contents for past …
> maint: remove interstitial linux subdir from S3 publish

- README.md
- eventpublisher/eventpublisher.go
- eventpublisher/eventpublisher_test.go
- logsapi/server.go
- main.go
- main_test.go
* Partially address #101 
This provides a means to configure just the connect timeout, probably the most important of the timeout settings, so limiting scope to just that.
* A new env variable HONEYCOMB_CONNECT_TIMEOUT can be used to customize the HTTP transport connection timeout for the underlying libhoney-go client so that when there are network connectivity issues, batch upload will fail faster and not hang for the full duration of the batch upload timeout. The default connection timeout is set to 3 seconds if not specified. This closes out a portion of issue #101, as it's only handling connect timeout for now. Limiting network connection timeouts is critical for a Lambda extension as it's possible for an extension to extend the duration of a function invocation and result in function …
> feat: configurable HTTP transport connect timeout

- eventpublisher/eventpublisher.go
- eventpublisher/eventpublisher_test.go
- libhoney 1.18.0 includes GOARCH in the user-agent already, so the lambda extension does not need to repeat it
Difference in user-agent after this change:
```diff
- libhoney-go/1.18.0 honeycomb-lambda-extension/1.2.3 (amd64) go/1.19.1 (linux/amd64)
+ libhoney-go/1.18.0 honeycomb-lambda-extension/1.2.3 go/1.19.1 (linux/amd64) 
```
- remove explicit GOARCH add in user-agent addition
- test that GOARCH still appears in the final user-agent
> remove duplicate GOARCH in user-agent

- README.md
- publish.sh
Updates the list of AWS regions we publish the lambda extension to. Also adds docs to how we source the list of regions and how we determine which platforms it supports.
- Closes #121 
- Update `publish.sh` with new regions
- Add section to README on how to get list of regions including supported platforms
- Rename from `REGIONS_NO_ARCH` and `REGIONS_WITH_ARCH` to `REGIONS_NO_ARM` and `REGIONS-WITH_ARM` for better clarity
- We published a dev tag for `ap-southeast-4` and `us-east-1` to confirm the layer appeared as expected in both regions (`honeycomb-lambda-extension-x86_64-v11-1-1-dev` in both, `honeycomb-lambda-extension-arm64-v11-1-1-dev` in `us-east-1`). Also clicked into each of the other new regions to confirm an empty layer page, so we have permissions to publish there.
> maint: Update AWS regions we publish to

- CHANGELOG.md
- new release v11.1.1
- update changelog with changes since last release
- post-release steps:
- prepped docs PR to be updated and merged once this is released
- prepped `release.json` artifact to double-check and upload to github release page
> rel: prepare release v11.1.1

- LICENSES/github.com/facebookgo/clock/LICENSE
- LICENSES/github.com/facebookgo/limitgroup/license
- LICENSES/github.com/facebookgo/muster/license
- LICENSES/github.com/honeycombio/honeycomb-lambda-extension/LICENSE
- LICENSES/github.com/honeycombio/honeycomb-lambda-extension/NOTICE
- LICENSES/github.com/honeycombio/libhoney-go/LICENSE
- LICENSES/github.com/honeycombio/libhoney-go/NOTICE
- LICENSES/github.com/klauspost/compress/LICENSE
- LICENSES/github.com/klauspost/compress/internal/snapref/LICENSE
- LICENSES/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt
- LICENSES/github.com/sirupsen/logrus/LICENSE
- LICENSES/github.com/vmihailenco/msgpack/v5/LICENSE
- LICENSES/github.com/vmihailenco/tagparser/v2/LICENSE
- LICENSES/golang.org/x/sys/unix/LICENSE
- LICENSES/gopkg.in/alexcesaro/statsd.v2/LICENSE
- RELEASING.md
It is a legal requirement to include the license of any software used to build distributable artefacts. This PR uses [go-licenses](https://github.com/google/go-licenses) to determine and extract the license files for the dependencies for buildevents.
It also updates the releasing.md to include the steps to ensure this is updated as part of the release process.
- Add licenses directory that contains the license for each project dependency
- Updates releasing.md with steps to re-create the set of dependency licenses
> maint: Add dependency licenses

- .circleci/config.yml
- Use temp credentials for CI
- Use the CircleCI OIDC integration
- bump the aws orb versin
> chore: use temp credentials for CI

- .github/dependabot.yml
This will use CODEOWNERS instead
> maint(deps): remove reviewers from dependabot.yml

- CHANGELOG.md
- logsapi/server.go
- logsapi/server_test.go
If the app that we're forwarding telemetry for is doing it's own
sampling, we want to honor that
Closes #145
> fix: forward the sample rate from the message

- .circleci/config.yml
- go.mod
- go.sum
- CVE-2025-22871 is fixed by using a later release of Go. While this extension is likely not vulnerable unless AWS gets cracked, it's still useful to update dependencies and the Go version.
- Bump go to 1.24
- Bump compress to v1.18
- Bump x/sys to v0.32
> maint: Bump go to 1.24 and some dependencies
